#ifndef __CONFIG__
#define __CONFIG__

#define BUT_PIN 4

#define SERVO_PIN 3

#define POT_PIN A0

#define LCD_SDA_PIN A4
#define LCD_SCL_PIN A5

enum State {NORMAL,ALLARMTOOHIGH,ALLARMTOOHIGHCRITIC,PREALLARMTOOHIGH,ALLARMTOOLOW};


#endif